### ISSUE TITLE
exhibit.py not working

### ISSUE THREAD

**Issue by mctosima** [sathyapriyaa-sketch/TEAM-Mirage#1]
Hi There. I'm just started to learn TOI and wanted to know about this, then I randomly searched about TOI on GitHub and found this repo.

However, It looks that the exhibit.py is not running smoothly on me. Yes, it can be run from the terminal. At first, it opened my webcam, but no window was showed up, then the program closed. It generates the output.avi files with 6kb size but unplayable.

While the other code, such as combo_lab and conversion, could run smoothly and pop out a display window.

It would be constructive if you could tell me something regarding this.
Thank you

**Comment by sathyapriyaa-sketch** [comment]
Hey! @mctosima, Check this video for up to 2 mins 17 sec, I've demonstrated how to execute this. Link: https://drive.google.com/file/d/15IXEI3aSfl8_o0QFFIKmfG5i-vZ179Ls/view?usp=sharing Let me know if you face any more difficulties in execution.
